export const siteName = 'Kaffeparty';
export const siteTitle = 'Kaffeparty up your life';
export const author = 'robboten';
export const copyYear = 2022;

export const host = "http://localhost:3000";

export const sitePages = [
    {
        name: 'Products',
        path: 'products',
        headerbody: 'These are our products. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quam nemo umquam voluptatem appellavit, appellat; Quamquam haec quidem praeposita recte et reiecta dicere licebit. Odium autem et invidiam facile vitabis. Quando enim Socrates, qui parens philosophiae iure dici potest, quicquam tale fecit? Duo Reges: constructio interrete. Illa tamen simplicia, vestra versuta.',
        title: 'Våra produkter'
    },
    { name: 'Events', path: 'events', title: 'Våra events' },
    { name: 'About', path: 'about',  title: 'Om oss' },
]

export const mainPageHeaders = [
    { key: 1, title: "Vilka är vi?", align: false, span: 8, src: "http://www.dvo.com/newsletter/monthly/2022/october/images/hot-drink.jpeg" },
    { key: 2, title: "Vad gör vi?", align: true, span: 8, src: "https://libreshot.com/wp-content/uploads/2016/04/chocolate-and-coffee.jpg" },
    { key: 3, title: "Varför oss?", align: false, span: 10, src: "https://www.jazzedongrains.com/wp-content/uploads/2022/05/Cover-story-arabica-2.jpg" },
    { key: 4, title: "Kaffeparty, så fungerar det!", align: true, span: 8, src: "https://live.staticflickr.com/65535/51196341817_db191250d1_b.jpg" }
]

export const lorem = [
    {
        text: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quam nemo umquam voluptatem appellavit, appellat; Quamquam haec quidem praeposita recte et reiecta dicere licebit. Odium autem et invidiam facile vitabis. Quando enim Socrates, qui parens philosophiae iure dici potest, quicquam tale fecit? Duo Reges: constructio interrete. Illa tamen simplicia, vestra versuta. Quid enim me prohiberet Epicureum esse, si probarem, quae ille diceret? Si enim ad populum me vocas, eum. </p>        <p>At iam decimum annum in spelunca iacet. Nihil opus est exemplis hoc facere longius. Cum audissem Antiochum, Brute, ut solebam, cum M. Quis enim confidit semper sibi illud stabile et firmum permansurum, quod fragile et caducum sit? Vos autem cum perspicuis dubia debeatis illustrare, dubiis perspicua conamini tollere. Cave putes quicquam esse verius. Non enim iam stirpis bonum quaeret, sed animalis. Quid ergo aliud intellegetur nisi uti ne quae pars naturae neglegatur? Non ego tecum iam ita iocabor, ut isdem his de rebus, cum L. </p>    <p>Ita redarguitur ipse a sese, convincunturque scripta eius probitate ipsius ac moribus. Quem Tiberina descensio festo illo die tanto gaudio affecit, quanto L. Est enim tanti philosophi tamque nobilis audacter sua decreta defendere. Et hercule-fatendum est enim, quod sentio -mirabilis est apud illos contextus rerum. Hoc loco discipulos quaerere videtur, ut, qui asoti esse velint, philosophi ante fiant. Itaque si aut requietem natura non quaereret aut eam posset alia quadam ratione consequi. Ergo id est convenienter naturae vivere, a natura discedere. Quoniam, si dis placet, ab Epicuro loqui discimus. Huius, Lyco, oratione locuples, rebus ipsis ielunior. Nec vero intermittunt aut admirationem earum rerum, quae sunt ab antiquis repertae, aut investigationem novarum. </p>",
    },
]
export const shortLatin = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quam nemo umquam voluptatem appellavit, appellat; Quamquam haec quidem praeposita recte et reiecta dicere licebit. Odium autem et invidiam facile vitabis. Quando enim Socrates, qui parens philosophiae iure dici potest, quicquam tale fecit? Duo Reges: constructio interrete. Illa tamen simplicia, vestra versuta.";

export const latinSm = `Uisque justonul maurisma eratfus quispr bibendu dapibus urnaut enas sse. Facilis lacuse pharetra miin consect lla que leocras sceleris quamve. Lectuss potenti nibhnull adipisci habitas ent nulla magnapro. Aenean tur tempusp iquam antenunc malesuad estmorbi enas suspendi element. Sed cras estmae malesu dapibusc pellente velit tempor faucib. Morbi lla maecenas aliqua ger senectus.`;

export const latinLgold = `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quam nemo umquam voluptatem appellavit, appellat; Quamquam haec quidem praeposita recte et reiecta dicere licebit. Odium autem et invidiam facile vitabis. Quando enim Socrates, qui parens philosophiae iure dici potest, quicquam tale fecit? Duo Reges: constructio interrete. Illa tamen simplicia, vestra versuta. Quid enim me prohiberet Epicureum esse, si probarem, quae ille diceret? Si enim ad populum me vocas, eum. </p>
<p>At iam decimum annum in spelunca iacet. Nihil opus est exemplis hoc facere longius. Cum audissem Antiochum, Brute, ut solebam, cum M. Quis enim confidit semper sibi illud stabile et firmum permansurum, quod fragile et caducum sit? Vos autem cum perspicuis dubia debeatis illustrare, dubiis perspicua conamini tollere. Cave putes quicquam esse verius. Non enim iam stirpis bonum quaeret, sed animalis. Quid ergo aliud intellegetur nisi uti ne quae pars naturae neglegatur? Non ego tecum iam ita iocabor, ut isdem his de rebus, cum L. </p>
<p>Ita redarguitur ipse a sese, convincunturque scripta eius probitate ipsius ac moribus. Quem Tiberina descensio festo illo die tanto gaudio affecit, quanto L. Est enim tanti philosophi tamque nobilis audacter sua decreta defendere. Et hercule-fatendum est enim, quod sentio -mirabilis est apud illos contextus rerum. Hoc loco discipulos quaerere videtur, ut, qui asoti esse velint, philosophi ante fiant. Itaque si aut requietem natura non quaereret aut eam posset alia quadam ratione consequi. Ergo id est convenienter naturae vivere, a natura discedere. Quoniam, si dis placet, ab Epicuro loqui discimus. Huius, Lyco, oratione locuples, rebus ipsis ielunior. Nec vero intermittunt aut admirationem earum rerum, quae sunt ab antiquis repertae, aut investigationem novarum. </p>
<p>Ex quo, id quod omnes expetunt, beate vivendi ratio inveniri et comparari potest. Ut scias me intellegere, primum idem esse dico voluptatem, quod ille don. Ita fit cum gravior, tum etiam splendidior oratio. Quae cum magnifice primo dici viderentur, considerata minus probabantur. Nemo nostrum istius generis asotos iucunde putat vivere. Roges enim Aristonem, bonane ei videantur haec: vacuitas doloris, divitiae, valitudo; </p>`;

export const latinLg = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quam nemo umquam voluptatem appellavit, appellat; Quamquam haec quidem praeposita recte et reiecta dicere licebit. Odium autem et invidiam facile vitabis. Quando enim Socrates, qui parens philosophiae iure dici potest, quicquam tale fecit? Duo Reges: constructio interrete. Illa tamen simplicia, vestra versuta. Quid enim me prohiberet Epicureum esse, si probarem, quae ille diceret? Si enim ad populum me vocas, eum.

At iam decimum annum in spelunca iacet. Nihil opus est exemplis hoc facere longius. Cum audissem Antiochum, Brute, ut solebam, cum M. Quis enim confidit semper sibi illud stabile et firmum permansurum, quod fragile et caducum sit? Vos autem cum perspicuis dubia debeatis illustrare, dubiis perspicua conamini tollere. Cave putes quicquam esse verius. Non enim iam stirpis bonum quaeret, sed animalis. Quid ergo aliud intellegetur nisi uti ne quae pars naturae neglegatur? Non ego tecum iam ita iocabor, ut isdem his de rebus, cum L.

Ita redarguitur ipse a sese, convincunturque scripta eius probitate ipsius ac moribus. Quem Tiberina descensio festo illo die tanto gaudio affecit, quanto L. Est enim tanti philosophi tamque nobilis audacter sua decreta defendere. Et hercule-fatendum est enim, quod sentio -mirabilis est apud illos contextus rerum. Hoc loco discipulos quaerere videtur, ut, qui asoti esse velint, philosophi ante fiant. Itaque si aut requietem natura non quaereret aut eam posset alia quadam ratione consequi. Ergo id est convenienter naturae vivere, a natura discedere. Quoniam, si dis placet, ab Epicuro loqui discimus. Huius, Lyco, oratione locuples, rebus ipsis ielunior. Nec vero intermittunt aut admirationem earum rerum, quae sunt ab antiquis repertae, aut investigationem novarum.

Ex quo, id quod omnes expetunt, beate vivendi ratio inveniri et comparari potest. Ut scias me intellegere, primum idem esse dico voluptatem, quod ille don. Ita fit cum gravior, tum etiam splendidior oratio. Quae cum magnifice primo dici viderentur, considerata minus probabantur. Nemo nostrum istius generis asotos iucunde putat vivere. Roges enim Aristonem, bonane ei videantur haec: vacuitas doloris, divitiae, valitudo;`;


export const latinMd = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quam nemo umquam voluptatem appellavit, appellat; Quamquam haec quidem praeposita recte et reiecta dicere licebit. Odium autem et invidiam facile vitabis. Quando enim Socrates, qui parens philosophiae iure dici potest, quicquam tale fecit? Duo Reges: constructio interrete. Illa tamen simplicia, vestra versuta. Quid enim me prohiberet Epicureum esse, si probarem, quae ille diceret? Si enim ad populum me vocas, eum.

At iam decimum annum in spelunca iacet. Nihil opus est exemplis hoc facere longius. Cum audissem Antiochum, Brute, ut solebam, cum M. Quis enim confidit semper sibi illud stabile et firmum permansurum, quod fragile et caducum sit? Vos autem cum perspicuis dubia debeatis illustrare, dubiis perspicua conamini tollere. Cave putes quicquam esse verius. Non enim iam stirpis bonum quaeret, sed animalis. Quid ergo aliud intellegetur nisi uti ne quae pars naturae neglegatur? Non ego tecum iam ita iocabor, ut isdem his de rebus, cum L. `;


export const json_latinMd = { text: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quam nemo umquam voluptatem appellavit, appellat; Quamquam haec quidem praeposita recte et reiecta dicere licebit. Odium autem et invidiam facile vitabis. Quando enim Socrates, qui parens philosophiae iure dici potest, quicquam tale fecit? Duo Reges: constructio interrete. Illa tamen simplicia, vestra versuta. Quid enim me prohiberet Epicureum esse, si probarem, quae ille diceret? Si enim ad populum me vocas, eum. </p><p>At iam decimum annum in spelunca iacet. Nihil opus est exemplis hoc facere longius. Cum audissem Antiochum, Brute, ut solebam, cum M. Quis enim confidit semper sibi illud stabile et firmum permansurum, quod fragile et caducum sit? Vos autem cum perspicuis dubia debeatis illustrare, dubiis perspicua conamini tollere. Cave putes quicquam esse verius. Non enim iam stirpis bonum quaeret, sed animalis. Quid ergo aliud intellegetur nisi uti ne quae pars naturae neglegatur? Non ego tecum iam ita iocabor, ut isdem his de rebus, cum L. </p>" }